### ISSUE TITLE
can read chats but not send them. also cant click X to close chats.

### ISSUE THREAD

**Issue by jackonmcnapkin** [tersiswilvin/Roblox-2019-Old-Theme#103]
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

google chrome

### Page URL

https://www.roblox.com/home

### Channel

Experimental

### Type

CSS

### Describe the Problem

as you can see, i can read all my previous chats, but there is no chat bar. there is also no x to close out of these chats
![image](https://github.com/user-attachments/assets/277d6d94-fffd-4b85-9c54-eddaf2aa9845)
![image](https://github.com/user-attachments/assets/75518178-d391-4cc0-a854-d9f9c12a77d4)

**Comment by tersiswilvin** [comment]
Cannot reproduce, what are your current settings?
![image](https://github.com/user-attachments/assets/fbb9977a-bb35-4c14-9f7c-e5b3bde0856d)

**Comment by tersiswilvin** [comment]
> Cannot reproduce, what are your current settings? ![image](https://private-user-images.githubusercontent.com/52929976/388598672-fbb9977a-bb35-4c14-9f7c-e5b3bde0856d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMDU5NTYsIm5iZiI6MTczMjIwNTY1NiwicGF0aCI6Ii81MjkyOTk3Ni8zODg1OTg2NzItZmJiOTk3N2EtYmIzNS00YzE0LTlmN2MtZTViM2JkZTA4NTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDE2MTQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxMTI3ZmJlMGE2YWQwMWEzNGQ0MTA3ZmQ5OTA4Njc5NzkyY2YzYTQzYjg5MTQxMTVhYzU4YTBhZGEwNTdlNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HGdO2y2AFItJ1yV_7QdcmH7Hud_Rqd86Sbi_cq1dsCo)

I suspect it's an issue caused by chat header label width and with the party chat icon being there.

**Comment by jackonmcnapkin** [comment]
nevermind, i am no longer having the issue.

**Comment by Meolsei** [comment]
I've also run into this issue, any help here?

**Comment by vinesrdacoolest** [comment]
The Loading Screen Roblox is Broken
