### ISSUE TITLE
clicking on a game that friends are playing is bugged slightly

### ISSUE THREAD

**Issue by jackonmcnapkin** [tersiswilvin/Roblox-2019-Old-Theme#109]
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

google chrome

### Page URL

https://www.roblox.com/home

### Channel

Experimental

### Type

CSS

### Describe the Problem

when i clicked on the bottom part of a game that my friends were playing, i clicked on the part with their profile pictures to see who was playing. when the menu popped up, the lines were a little off and there were no usernames attached to the profile pictures

![image](https://github.com/user-attachments/assets/f4eb1247-ef92-423d-b08a-70bc6ffa4b1c)
![image](https://github.com/user-attachments/assets/7edec43a-17f2-4e8d-93cd-08c1fa06d027)

**Comment by tersiswilvin** [comment]
This is unfortunately a roblox css issue with floats, however I'll look into fixing it for RLOT.
