### ISSUE TITLE
"Normal" Roblox favicon showing on DevForum

### ISSUE THREAD

**Issue by ghost** [tersiswilvin/Roblox-2019-Old-Theme#19]
### Browser

Google Chrome

### Channel

Experimental

### Page URL

https://devforum.roblox.com/

### Describe the Problem

The DevForum favicon is not showing and is being replaced with the favicon selected in the Legacy Site Restoration script. It would be nice to see options to change this to match with the Site Brand Year (example, site brand is set to 2016, uses 2016 developer/studio icon).

**Comment by tersiswilvin** [comment]
I'll look into fixing this as well as adding that option for you.

**Comment by ghost** [comment]
It looks like this is now been added into the script and it works!
