### ISSUE TITLE
Add back the Friends Playing sort

### ISSUE THREAD

**Issue by ghost** [tersiswilvin/Roblox-2019-Old-Theme#23]
### Type

CSS

### Describe the Feature

It would be a nice thing to see the Friends Playing sort come back and remove all the other ones that were added as they serve ABSOLUTELY no purpose to me on the home page! (Since it doesn't like Roblox is going to do it: https://devforum.roblox.com/t/bring-back-the-friends-playing-sort/2333755)

![image](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/77752310/d6d062bd-a12b-4f25-a7d4-2dbd7d502215)

**Comment by tersiswilvin** [comment]
Unfortunately there is no way to bring back the Friends Activity using just CSS alone as this would require requesting the API to get the friend sorts if the api still even exist, as for removing the games page like game cards I can look to see what were used in 2019 and remove the ones I don't see used back then.

**Comment by ghost** [comment]
> Unfortunately there is no way to bring back the Friends Activity using just CSS alone as this would require requesting the API to get the friend sorts if the api still even exist, as for removing the games page like game cards I can look to see what were used in 2019 and remove the ones I don't see used back then.

Would you be able to use JS for the Friends Playing sort as I'm sure the APIs still exist or how will it say [Number]Friend(s) Playing on the game cards?

**Comment by tersiswilvin** [comment]
> > Unfortunately there is no way to bring back the Friends Activity using just CSS alone as this would require requesting the API to get the friend sorts if the api still even exist, as for removing the games page like game cards I can look to see what were used in 2019 and remove the ones I don't see used back then.
> 
> Would you be able to use JS for the Friends Playing sort as I'm sure the APIs still exist or how will it say [Number]Friend(s) Playing on the game cards?

I can look into if that API still exists.

**Comment by tersiswilvin** [comment]
Closing as I've had no luck into restoring the functionality of this sort, will restore if there's good progress made.
