### ISSUE TITLE
Extend the Tix Option's Impact on the Website(s)

### ISSUE THREAD

**Issue by haydengriz** [tersiswilvin/Roblox-2019-Old-Theme#25]
### Type

CSS

### Describe the Feature

please change leftover text and icons that mentions Robux (when the Tix Option is applied of course)

https://www.roblox.com/Reference/StyleGuide#

https://www.roblox.com/premium/membership?ctx=leftnav

https://www.roblox.com/catalog 

and when you click the tix icon it comes up with the two buttons "Buy Robux" and "[NUMBER] Robux" 

I hope I was able to explain it well enough to you
(I would've included screenshots but the problem is my computer is junk)

**Comment by tersiswilvin** [comment]
Hi [HAYDENCRAFT2008](https://github.com/HAYDENCRAFT2008) thank you for suggesting, I'll look into extending the robux to tix option however the {NUM} Robux while it is sorta possible I notice the method I use doesn't work correctly for those with lower amounts so until I can find a better alternative it will remain {NUM} Robux.

**Comment by haydengriz** [comment]
thank you again for your consideration! Tickets feel much less corporate than Robux in general.
