### ISSUE TITLE
Reconstruct login page

### ISSUE THREAD

**Issue by ghost** [tersiswilvin/Roblox-2019-Old-Theme#26]
### Type

Both

### Describe the Feature

Is it possible to add (obviously a non functional) Facebook option back, and remove One time code and Quick login options and basically revert everything back to how it was, like this?

![image](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/77752310/eaa810ed-ded3-4e23-9702-0eab7386de17)

**Comment by tersiswilvin** [comment]
This can definitely be done with JS.

**Comment by tersiswilvin** [comment]
I can try seeing about adding the button back not sure if it will be JS or CSS (this will be up to whatever is possible) as for removing quick login and one time code I will definitely look into that as I haven't checked login in a while so they must had been added recently.
