### ISSUE TITLE
Implementing this onto the Homescreen

### ISSUE THREAD

**Issue by sha4owz** [tersiswilvin/Roblox-2019-Old-Theme#32]
### Type

Both

### Describe the Feature

https://www.roblox.com/feeds/
Its a untouched legacy site that remind me of forums.
By adding it, you could make a half working replica of fourms
Check it out: https://www.roblox.com/feeds/
Photo:
![wednnf](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/138281770/a4b8a561-e888-4b43-a89e-c7c0dfe0476d)
(Photo is using THIS theme, still looks basicly the same without tho.)

**Comment by ghost** [comment]
It's already there with the legacy site restoration script, but making it appear on the home screen would be amazing!

**Comment by tersiswilvin** [comment]
I can make an option in the setting to have it appear in the home page (with the blog).

**Comment by sha4owz** [comment]
Yes please, just under favourites. Also include the Status type bar at the top

**Comment by ghost** [comment]
> Yes please, just under favourites. Also include the Status type bar at the top

I would enjoy this, the nostalgia coming back!

**Comment by sha4owz** [comment]
> I can make an option in the setting to have it appear in the home page (with the blog).

PLEASEEEE ADD IT TO PROJECTT!!!

**Comment by tersiswilvin** [comment]
This has been integrated into LegacySiteRestoration as an option.
