### ISSUE TITLE
Profile tab text wrong color

### ISSUE THREAD

**Issue by ShokCat** [tersiswilvin/Roblox-2019-Old-Theme#35]
### Browser

FireFox

### Page URL

https://www.roblox.com/home

### Channel

Release

### Type

CSS

### Describe the Problem

I have no clue if its just me but for some reason the color for profile tab is the same color as the avatar tab

![image](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/126297961/5abf1837-1876-448d-bd97-e74a134b1712)
![image](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/126297961/b4975323-912d-40ae-a688-e4aa108d4170)

**Comment by haydengriz** [comment]
huh. It happened to me too

**Comment by tersiswilvin** [comment]
This is intended and is not a bug.

![image](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/52929976/a9c75196-7d04-413a-904b-93fd18e7a3d6)
