### ISSUE TITLE
Is a fix coming for this???????

### ISSUE THREAD

**Issue by sha4owzz** [tersiswilvin/Roblox-2019-Old-Theme#38]
### Browser

Google Chrome

### Page URL

https://www.roblox.com/home

### Channel

Release

### Type

CSS

### Describe the Problem

this applies for experimental and release.

The home screen s bugged because of the new recommended for you thing????
my screenshots are awful bright, but u can see the bug

image:
![image](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/146622929/bf048dca-0ab0-43fe-a9f9-717296df5858)

**Comment by ghost** [comment]
You might want to calm down a little bit, as it looks like that only got released today (for me anyway) not being rude or anything but why send that issue report literally right after the new sort gets released

**Comment by tersiswilvin** [comment]
I don't have this update right now, I'll check on my other alts to see if they have it, and if they do to apply a fix.

**Comment by tersiswilvin** [comment]
Moved this to #54.
