### ISSUE TITLE
do you have any old avatar editor html

### ISSUE THREAD

**Issue by Aeplet** [tersiswilvin/Roblox-2019-Old-Theme#39]

**Comment by ghost** [comment]
Issue #9, comment 2 it was mentioned by me and tersiswilvin replied regarding it

**Comment by tersiswilvin** [comment]
https://codepen.io/210/pen/NjxOaO

**Comment by Aeplet** [comment]
2017E man

**Comment by tersiswilvin** [comment]
I do not have any 2017E archives, otherwise the avatar editor would had been 100% finished on my theme.

**Comment by Aeplet** [comment]
that IS 2017E, i meant i wanted 2017M-2019E

**Comment by tersiswilvin** [comment]
I don't have any May 2017+ archives, like I said prior, if I did I would had already posted it.

**Comment by ErikaXGH** [comment]
> https://codepen.io/210/pen/NjxOaO

thanks
