### ISSUE TITLE
Typo in settings

### ISSUE THREAD

**Issue by RUvlad1** [tersiswilvin/Roblox-2019-Old-Theme#4]
It says "Source San Pro" instead of "Source Sans Pro"

![image](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/60317461/9df0d580-1f5e-4368-a87b-a406b3eb98a2)

**Comment by tersiswilvin** [comment]
Thanks, not sure how I missed that, but I'll fix this for the upcoming 1.3 update.
