### ISSUE TITLE
Group list too thin

### ISSUE THREAD

**Issue by JSkes** [tersiswilvin/Roblox-2019-Old-Theme#40]
### Browser

Google Chrome

### Page URL

https://www.roblox.com/groups/[id here]/[name here]

### Channel

Release

### Type

CSS

### Describe the Problem

Can you please make the group list wider? It looks super awkward with RoSeal pending groups. Plus there's overlapping text:
![image](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/71411219/04053055-2ef7-4ca2-8b33-5fe90324396e)
Also it looks even worse with the RoSeal group organiser feature:
![image](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/71411219/3e23113c-45b1-4c93-a3f1-2e32859ea4ea)
If you can't/won't do it, please tell me how I can fix it myself, it's such an eye sore to look at and it's super annoying.

**Comment by tersiswilvin** [comment]
Hi I am unable to replicate the issue in the second screenshot, do you have any other roblox extensions enabled?

**Comment by JSkes** [comment]
No, I have no extensions enabled other than RoSeal, with the beta group organiser feature on, that's all I was using in the screenshot.
***Correction***: The feature in RoSeal is called Group organisation customisation in the Groups tab.
***Correction 2***: I've just now realised I was using an older version of this theme, and yes I'm no longer able to replicate the 2nd screenshot anymore.

**Comment by tersiswilvin** [comment]
> No, I have no extensions enabled other than RoSeal, with the beta group organiser feature on, that's all I was using in the screenshot. _**Correction**_: The feature in RoSeal is called Group organisation customisation in the Groups tab. _**Correction 2**_: I've just now realised I was using an older version of this theme, and yes I'm no longer able to replicate the 2nd screenshot anymore.

I did notice a small issue with the roseal beta group organizer feature on the latest where the side bar was to wide however this should be fixed on the latest and experimental releases.

**Comment by tersiswilvin** [comment]
I'm gonna close this as I believe it is fixed, if there is still an issue present please feel free to reopen this with more additional info.

**Comment by JSkes** [comment]
Oh it's fixed? Haven't noticed that. However I still believe it's too thin, personally I think it should be as wide as the top Joined and Pending tabs

**Comment by tersiswilvin** [comment]
I'll try looking into making it match the width, but I won't be able to do it anytime soon since I got my wisdon teeth recently removed.

**Comment by JSkes** [comment]
Maybe you could tell me how to do it on my own so I can do it myself and you don't have to
