### ISSUE TITLE
is there an option for old "about me" edit button.

### ISSUE THREAD

**Issue by wnzf** [tersiswilvin/Roblox-2019-Old-Theme#45]
### Type

Both

### Describe the Feature

is there an option for the old about me edit button, like before december 2023 i think.

**Comment by ghost** [comment]
This was removed for a reason. The functionality was that you'd edit your description through your user settings in 2019.

**Comment by wnzf** [comment]
> This was removed for a reason. The functionality was that you'd edit your description through your user settings in 2019.

Oh.

**Comment by tersiswilvin** [comment]
> This was removed for a reason. The functionality was that you'd edit your description through your user settings in 2019.

Also in the javascript they can also turn it off the setting is under `Settings.Global.LegacyEditDescription.Enabled` just change true to false.
Edit: Going to close as I believe this is fixed.
