### ISSUE TITLE
I cannot view my gears on avatar page

### ISSUE THREAD

**Issue by wnzf** [tersiswilvin/Roblox-2019-Old-Theme#50]
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

librewolf

### Page URL

https://roblox.com/my/avatar

### Channel

Release

### Type

CSS

### Describe the Problem

I noticed that issue back in november 2023, but i reported that bug just now lol

![Screenshot 2024-03-07 at 20 39 29](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/131486833/b5832cc4-617e-429f-8443-90e54d893323)

**Comment by tersiswilvin** [comment]
Disable ``Five column Avatar Editor`` to access your gears and other Accessories.
![image](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/52929976/ae8b33f8-eaf0-4636-9e91-8f4033897756)

**Comment by wnzf** [comment]
oh lord, i m so sorry, i could not believe that it was that simple..
thank you again.

**Comment by tersiswilvin** [comment]
> oh my god, i m so sorry, i could not believe that i m struggling with that since november 😭

No worries.
