### ISSUE TITLE
Compatibility for Melo's "2014-eseque ROBLOX" theme

### ISSUE THREAD

**Issue by haydengriz** [tersiswilvin/Roblox-2019-Old-Theme#51]
### Type

JavaScript

### Describe the Feature

To be more specific, I was hoping that things like the "My Feed" page (partially the button) and the forum button could be made to fit better with Melo's theme, more specifically for December 2014 and maybe even August 2014. There's probably some other stuff I'm missing but these were the most obvious ones

**Comment by haydengriz** [comment]
and yes this is for "Legacy Site Restoration"

**Comment by tersiswilvin** [comment]
Not Planned at this time.
