### ISSUE TITLE
Dismiss and Join buttons in notifications tab are collapsed a little bit

### ISSUE THREAD

**Issue by wnzf** [tersiswilvin/Roblox-2019-Old-Theme#52]
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

vivaldi

### Page URL

roblox.com/home

### Channel

Release

### Type

CSS

### Describe the Problem

Title says it all
![Screenshot 2024-03-20 at 19 23 01](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/131486833/0fac9d74-2e40-40ec-afef-405c19d4be27)

**Comment by tersiswilvin** [comment]
I'll look into this when I get it in the notifications.
