### ISSUE TITLE
Red theme selections doesnt change anything (the 2017 logo stays white)

### ISSUE THREAD

**Issue by Hellforag** [tersiswilvin/Roblox-2019-Old-Theme#53]
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

Waterfox

### Page URL

All Roblox URLS

### Channel

Release

### Type

CSS

### Describe the Problem

explained in title

**Comment by ghost** [comment]
Can you send a screenshot? Currently, the red icon logo configuration option only seems to change it on the Robux buy page. In the navbar at the top, the white Roblox logo was never red, unless it was the old pre-2017 one. If you're talking about the favicon, you need Legacy Site Restoration, and you need to modify the value in line 67 to 2017L from 2018L

**Comment by tersiswilvin** [comment]
> ### Are you up-to-date?
> * [x]  I've confirmed that I am completely up-to-date.
> 
> ### Is the problem in Experimental?
> * [x]  I've verified that the problem persists in the Experimental Branch.
> 
> ### Browser
> Waterfox
> 
> ### Page URL
> All Roblox URLS
> 
> ### Channel
> Release
> 
> ### Type
> CSS
> 
> ### Describe the Problem
> explained in title

``Use 2017 Red icon logo`` only affects the Robux page and the system icon in Messages, the main site branding was never red other then on the signup page back then.
