### ISSUE TITLE
UPDATE IT ALREADY

### ISSUE THREAD

**Issue by assholegaming29** [tersiswilvin/Roblox-2019-Old-Theme#56]
### Type

CSS

### Describe the Feature

ROBLOX Finnaly decided on the page and UPDATE THE NEW FONT.
I AM ALREADY CRAVING for an update...

**Comment by mx-mic** [comment]
This is already on the [experimental channel](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/raw/Release/Dev/Experimental/src/RLOTExperimental.user.css). @tersiswilvin will release it to the stable channel once he feels like all his updates to his code works fully (I assume).

**Comment by tersiswilvin** [comment]
> ### Type
> CSS
> 
> ### Describe the Feature
> ROBLOX Finnaly decided on the page and UPDATE THE NEW FONT. I AM ALREADY CRAVING for an update...

The font will be released to MASTER once I verify the font is completely stable and ready to release, it also gives me time to iron out any potiental issues and add support for the home page and other A/B testing support roblox is rolling out lately.
