### ISSUE TITLE
V1 Homepage is broken

### ISSUE THREAD

**Issue by githubberguy** [tersiswilvin/Roblox-2019-Old-Theme#59]
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

Google Chrome

### Page URL

https://www.roblox.com/home

### Channel

Experimental

### Type

CSS

### Describe the Problem

bascially my robux when i put v1, is put in the wrong way, then no games appear like what i player recently, favorites, and etc.
![Screenshot 2024-05-04 212849](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/145132255/0b514df2-bbcb-40f9-87a5-0c18e7335653)

**Comment by githubberguy** [comment]
by the robux in the wrong position like this: 
![Uploading Screenshot 2024-05-04 213405.png…]()

**Comment by githubberguy** [comment]
robux in wrong position like this:
![Screenshot 2024-05-04 213405](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/145132255/d20e5aef-3116-4e20-8a9c-75ab464288e7)

**Comment by tersiswilvin** [comment]
Roblox is testing around 4 to 5 different home page A/B testing versions at this time, I can only test 3 of the 4/5, you might have one of the A/B testing layouts I don't have access to at this time.

**Comment by tersiswilvin** [comment]
Duplicate of #54.
