### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [tersiswilvin/Roblox-2019-Old-Theme#6]
Hi @tersiswilvin!

Sorry to bug you again! Does the LegacySiteRestoration experimental JS file currently do anything other than add a My Feed button to the sidebar and add the greeting and profile picture on the home page? Just curious to whether I should install it at this current stage. I assumed I'd have to download Tampermonkey, but if you wrote the code to work with something else specifically, please let me know!

**Comment by MX-Mic** [comment]
By the way, I just uninstalled DashBlox because I've realised installing the script added the greeting on the home page back.

**Comment by tersiswilvin** [comment]
Hi MX-Mic LegacySiteRestoration currently restores my feeds, the home header, events and also replaces the Get Premium button to Upgrade Now. You can find the settings within the script to turn off certain things you don't want or need (make sure to save for it to take effect). At this time the JS should be stable though I had put it under experimental as I am not to sure how stable it is at this time.

**Comment by ghost** [comment]
Thanks for the response! I'll keep it installed as I'm sure these features improve the experience, thanks. Also, what is the styleguide page? I've noticed in the settings that there is a option to change the 'Styleguide Page Theme', and I have no idea what it does.

**Comment by tersiswilvin** [comment]
The Style Guide Page theme modifies roblox style guide page when you visit [https://www.roblox.com/reference/styleguide](https://www.roblox.com/reference/styleguide)

**Comment by ghost** [comment]
Interesting, never knew about that page. Thanks, I'll close the issue/question now.
