### ISSUE TITLE
Favorites section and the "Continue Playing" and the see all button is missing

### ISSUE THREAD

**Issue by Clyde6790pGIT** [tersiswilvin/Roblox-2019-Old-Theme#60]
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

Brave

### Page URL

https://www.roblox.com/home

### Channel

Experimental

### Type

CSS and JS

### Describe the Problem

Multiple things have gone missing in the V3 homepage, yesterday the favorites disappeared and has stayed like that even after updating, the Continue playing and the see all button is also missing.
![Screenshot 2024-05-08 142239](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/78290310/7c1046c6-b282-4444-ba39-382d6abe3b08)

**Comment by ghost** [comment]
#54

**Comment by Clyde6790pGIT** [comment]
> #54

Ok, closing this as it appears to be a duplicate
