### ISSUE TITLE
The word "Robux" is duplicated

### ISSUE THREAD

**Issue by Clyde6790pGIT** [tersiswilvin/Roblox-2019-Old-Theme#62]
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

Brave

### Page URL

https://www.roblox.com/home

### Channel

Experimental

### Type

Both

### Describe the Problem

For some reason, having this stylus theme causes the word robux to duplicate, changing the currency to tickets makes it say "Robux Tickets".
![image](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/78290310/ff42cdf9-8201-41ac-9f01-0ca14cf1365d)
![image](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/78290310/cd676945-7788-47cf-9ea3-18e3da297cee)

**Comment by tersiswilvin** [comment]
Cannot replicate on my end, can you show me the entire popup html using inspect element?

**Comment by Clyde6790pGIT** [comment]
Hi, the issue has seemed to disappear ever since the last update, closing this as its probably not necessary anymore.

**Comment by tersiswilvin** [comment]
Apparently this is caused due to the roblox+ extension.
