### ISSUE TITLE
homepage bug

### ISSUE THREAD

**Issue by zIStrafe** [tersiswilvin/Roblox-2019-Old-Theme#64]
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

Google Chrome

### Page URL

https://www.roblox.com/home

### Channel

Release

### Type

CSS

### Describe the Problem

I've encountered a bug where this happens: https://imgur.com/a/u3GSy08

**Comment by ghost** [comment]
You may have a different A/B test version. See here for more info: https://github.com/tersiswilvin/Roblox-2019-Old-Theme/issues/54#issuecomment-2111518183

**Comment by tersiswilvin** [comment]
This shouldn't happen on experimental, are you sure you're using experimental and not master?
![image](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/52929976/cf9c4ef1-c3e5-4b6e-b761-c396be9a0bde)

**Comment by tersiswilvin** [comment]
Should be fixed in https://github.com/tersiswilvin/Roblox-2019-Old-Theme/commit/0d46f5c2cec3e77217cbf92fa9bfbcb3cb8b8c24.
