### ISSUE TITLE
Social link buttons are not the right website

### ISSUE THREAD

**Issue by x-Arden** [tersiswilvin/Roblox-2019-Old-Theme#69]
### Are you up-to-date?

- [x] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

Google Chrome

### Page URL

https://www.roblox.com/groups/ID

### Channel

Experimental

### Type

CSS

### Describe the Problem

The social link buttons are the wrong website.

https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/155813870/22ec69e9-00ff-4b5e-a612-e9cda1eb651a

**Comment by tersiswilvin** [comment]
I've been aware of this for awhile (though it's a height issue for me), just haven't have time this week to fix it yet. Hoping to fix it next week when I am free.

**Comment by tersiswilvin** [comment]
Should be now fixed in https://github.com/tersiswilvin/Roblox-2019-Old-Theme/commit/a70d698f1b92eba6aa6fa3af7c2c2fd8a2c202ad.
