### ISSUE TITLE
bug with the homepage

### ISSUE THREAD

**Issue by HazzyCap** [tersiswilvin/Roblox-2019-Old-Theme#70]
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [ ] I've verified that the problem persists in the Experimental Branch.

### Browser

Google Chrome

### Page URL

https://www.roblox.com/home

### Channel

Release

### Type

CSS

### Describe the Problem

hello, is my first time in github, soo i dunno what do here but
my problem is what the games are not appearing in the homepage
i recently installed the "roblox legacy old theme" and, idk what is happening.

if you ask if i installed the experimental, no, i dont install it

![dfgedgrfdbbdb](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/172859209/9c6d0ed4-c225-4d5b-a124-2d62f6adb772)
the homepage

![wfwefeg](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/172859209/043a6ee1-6f75-42ea-a8c1-b51d6767e414)
here is the config, may help, maybe.

if you can help me with this bug, it would be cool
thanks.

**Comment by tersiswilvin** [comment]
All of the above problems have already been fixed in experimental for the past month or two however I haven't published it due to the many dfferent A/B testing experiments roblox has been doing for the homepage for layout.

**Comment by HazzyCap** [comment]
oh, alright, thaks buddy, i guess
