### ISSUE TITLE
Roblox homapage is broken

### ISSUE THREAD

**Issue by G4M3R1233** [tersiswilvin/Roblox-2019-Old-Theme#72]
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

Firefox

### Page URL

https://www.roblox.com/home

### Channel

Release

### Type

CSS

### Describe the Problem

the roblox homepage is broken the games like "continue playing" is not showing. plz fix this

**Comment by tersiswilvin** [comment]
Can you please send a screenshot of the homepage.

**Comment by robisme** [comment]
![Screenshot (9)](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/171232301/df5f4e3c-e120-4532-8486-0f8b5a93da61)

**Comment by robisme** [comment]
![Uploading Screenshot (9).png…]()

**Comment by robisme** [comment]
![Screenshot (9)](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/171232301/7cf7ba25-bde2-4d63-a592-9d65e02c8b53)
