### ISSUE TITLE
homepage is bug

### ISSUE THREAD

**Issue by robisme** [tersiswilvin/Roblox-2019-Old-Theme#73]
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [x] I've verified that the problem persists in the Experimental Branch.

### Browser

Firefox

### Page URL

https://www.roblox.com/home

### Channel

Release

### Type

CSS

### Describe the Problem

![Screenshot (10)](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/171232301/3e1a3003-9813-48ec-8d3e-b8987f1bc324)

**Comment by tersiswilvin** [comment]
I believe this is fixed now.
