### ISSUE TITLE
Could you please center the homepage screen?

### ISSUE THREAD

**Issue by robisme** [tersiswilvin/Roblox-2019-Old-Theme#74]
### Type

CSS

### Describe the Feature

![4723f1a7dbf6ce9a9083624d7d0e4a3dbf20fc1b](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/171232301/e82db01f-617e-436a-aad5-e67fc425c191)

**Comment by tersiswilvin** [comment]
Added an option called "Home Ad Spacing" for home centering in https://github.com/tersiswilvin/Roblox-2019-Old-Theme/commit/f87ef1f170f507cf02f44f183d910e23e6f4bb27.
