### ISSUE TITLE
Homepage aligned to left side instead of center

### ISSUE THREAD

**Issue by lm3kn** [tersiswilvin/Roblox-2019-Old-Theme#75]
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

Microsoft Edge

### Page URL

https://www.roblox.com/home

### Channel

Experimental

### Type

CSS

### Describe the Problem

Likely as a result of the recent User Ads removal, I've noticed that now the homepage sticks to the left side of the screen instead of being centered.

![image](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/174393100/ef4c4703-3893-4010-936a-dcfbf8963830)

This has especially bothered me because I use the "keep sidebar open" feature in BTRoblox, in which there is no padding between the sidebar and the homepage content.

![image](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/174393100/c1d66ac5-9c23-46a3-8969-3cdef0afdf0f)

**Comment by tersiswilvin** [comment]
Content being left align is intentional, prior to ads being removed if you used an ad blocker the content would align to the left alittle due to there being no ads. However with roblox removing the ad html, it no longer provides a width and thus causes the left alignment.

**Comment by tersiswilvin** [comment]
Added an option called "Home Ad Spacing" for home centering in https://github.com/tersiswilvin/Roblox-2019-Old-Theme/commit/f87ef1f170f507cf02f44f183d910e23e6f4bb27.
