### ISSUE TITLE
Add The Options to have the new roblox icons (NOT LOGO) and the new thing on top

### ISSUE THREAD

**Issue by githubberguy** [tersiswilvin/Roblox-2019-Old-Theme#76]
### Type

CSS

### Describe the Feature

Bascially give us the options to have the old roblox icons (beacuse i am trying to do 2020) and this:
![image](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/145132255/f5ca3e91-21a8-43b0-b5be-28fab46be62e)
bascially i want the newer one (2024) of this^

make it an option

**Comment by githubberguy** [comment]
the header bascially.

**Comment by tersiswilvin** [comment]
Not Planned.
