### ISSUE TITLE
Roblox homepage bug

### ISSUE THREAD

**Issue by G4M3R1233** [tersiswilvin/Roblox-2019-Old-Theme#77]
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

Firefox

### Page URL

https://www.roblox.com/home

### Channel

Release

### Type

CSS

### Describe the Problem

![Screenshot (804)](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/173165946/33382ef8-b218-4ec9-932a-bbded39acd60)
Bugged homepage shows a stubby UI. can you fix it

**Comment by tersiswilvin** [comment]
This is issue has long been fixed in experimental.
