### ISSUE TITLE
When will you address the current theme? of 2019?

### ISSUE THREAD

**Issue by ismael37343** [tersiswilvin/Roblox-2019-Old-Theme#83]
### Type

CSS

### Describe the Feature

![ECDid9QWsAA7xzt](https://github.com/user-attachments/assets/6b6ebce6-041f-4c8b-a38f-ed61837d476d)

**Comment by githubguy217** [comment]
what does this mean?

**Comment by ismael37343** [comment]
the current theme 2019 and dark

**Comment by tersiswilvin** [comment]
Roblox Old Theme aims to restore the Legacy roblox theme from early 2019 to September 23 2019 before it was replaced with the new light and dark themes, plans to add the 2019 light and dark theme is not planned.

**Comment by ismael37343** [comment]
OK
