### ISSUE TITLE
VIP Server Tooltip Width Not Accurate to 2019

### ISSUE THREAD

**Issue by MicXDev** [tersiswilvin/Roblox-2019-Old-Theme#88]
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

Firefox

### Page URL

https://www.roblox.com/games/* (any game, in this example I used https://www.roblox.com/games/95206881)

### Channel

Experimental

### Type

CSS

### Describe the Problem

Hovering over the VIP servers help button on the game page compared to in 2019 (https://web.archive.org/web/20190822015235/https://www.roblox.com/games/95206881/Baseplate#!/about) reveals that the sizing for the dialog seems ever so slightly off, yet the CSS is the exact same.

Your theme
![Untitled](https://github.com/user-attachments/assets/7feb0544-03b7-433e-87fd-6a2f9b284ae9)

2019:
![Untitled-1](https://github.com/user-attachments/assets/0c6adbb6-532a-4716-8836-670e0c67adfa)

**Comment by tersiswilvin** [comment]
I see what's causing it, it appears to be a CSS layer position issue which shouldn't be hard to fix.
![image](https://github.com/user-attachments/assets/a25948eb-2a08-46d1-a5b5-9ac855f3e8d9)
