### ISSUE TITLE
Is the old 2016 catalog going to be added?

### ISSUE THREAD

**Issue by annoy205** [tersiswilvin/Roblox-2019-Old-Theme#89]
### Type

CSS

### Describe the Feature

There are some other themes that have made similar but I have never seen a 2016 theme do it. Thanks.

**Comment by MicXDev** [comment]
Duplicate of https://github.com/tersiswilvin/Roblox-Legacy-Old-Theme/issues/9?

**Comment by tersiswilvin** [comment]
Legacy Pages are not planned at this time.
