### ISSUE TITLE
RoGOLD ruins the theme

### ISSUE THREAD

**Issue by Clyde6790pGIT** [tersiswilvin/Roblox-2019-Old-Theme#90]
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

Firefox

### Page URL

https://www.roblox.com/home

### Channel

Experimental

### Type

Both

### Describe the Problem

When installing RoGold, the main page gets messed up even when all the customizations are turned off. (I only use rogold for live statistics such as live friend status)
![image](https://github.com/user-attachments/assets/0d6e6e83-7873-4ed5-abbe-d80e36633a28)

**Comment by tersiswilvin** [comment]
I can't replicate it with RoGold enabled, but I believe it's just a css stacking issue with how rogold injects its css. It should hopefully be fixed in the next experimental update.
