### ISSUE TITLE
Edit "About" button missing

### ISSUE THREAD

**Issue by junnlives** [tersiswilvin/Roblox-2019-Old-Theme#96]
### Are you up-to-date?

- [X] I've confirmed that I am completely up-to-date.

### Is the problem in Experimental?

- [ ] I've verified that the problem persists in the Experimental Branch.

### Browser

Brave v 1.70.117, tested on Chrome 129.0.6668.59

### Page URL

https://www.roblox.com/User.aspx?lD=

### Channel

Release

### Type

JavaScript

### NOTE: I can't submit this bug report without enabling the Experimental bug checkbox. Please fix that. I haven't tested if this persists in experimental or not.

Edit "about" button is missing in the userscript, without any extensions other than Stylus w/ sayorisocks' 2014-esque Roblox and Tampermonkey

Video: (ignore past 0:23, I forgot I had the userscript disabled)

https://github.com/user-attachments/assets/6c20d3f4-5774-46ae-97d4-89d0744a6140

**Comment by tersiswilvin** [comment]
LSR moves the description editing to the settings page like it was in 2019.

**Comment by tersiswilvin** [comment]
However a recent roblox update broke it, you will need to update LSR for the bugfix.
